# Site Settings
title: Emmanuel Bamba
url: 'https://ebitsdev.github.io'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Emmanuel Bamba
tagline: Front-End Developer
pic: ebamba_profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Over 8 years of experience in dealing with air traffic control procedures within the FAA and 19 years of 
experience in information technology working on both content design, development, and deployment, local and wide area 
network planning and installation for the private and government sectors.
Specifically designed, developed, and deployed web sites and applications, SharePoint applications or sites using 
JavaScript and various open source libraries for over 13 years.'
#sidebar links
email: ebamba@bitsnshine.com
phone: 240 516 8080
website: ebamba.com #do not add http://
linkedin: 
github: ebitsdev
twitter: '@ebamba'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-110181522-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
